apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xop3x1p32-go
  janus-idp.io/tekton: xop3x1p32-go
  backstage.io/kubernetes-id: xop3x1p32-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xop3x1p32-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
