apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xop3x1p32-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xop3x1p32-go 
  name: xop3x1p32-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xop3x1p32-go 
